### ISSUE TITLE
Update Topic Excel Doc

### ISSUE THREAD

**Issue by ktabarez** [missionfed/training#17]
Expand the opinion column. Exmaple:
Opinion
- On author 
- On learning experience
- How can we implement this here
- Examples?

**Comment by martinezrey** [comment]
### Updated Excel sheet:

[Pluralsight Topics.xlsx](https://github.com/missionfed/training/files/319019/Pluralsight.Topics.xlsx)

**Comment by ktabarez** [comment]
Rey can you put this on the wiki pls?

**Comment by martinezrey** [comment]
Kain it is up on wiki.
