### ISSUE TITLE
Project Leads Wanted

### ISSUE THREAD

**Issue by ktabarez** [missionfed/training#2]
Who can help with this. I will need 2 other developer. If you want help, you'll contribute to
- Manage the direction of this new initiative
- Providing feedback and ideas on how to make this process better
- Manage meeting outline
- If a project lead is out, you'll have to take jump in and direct the meeting
- Etc.

**Comment by ktabarez** [comment]
John and Rey have been assigned the GitHub lead role

**Comment by delljordan** [comment]
Project Leads are assigned, Kain and I, Plus John and Rey.

**Comment by ktabarez** [comment]
Correction: Aaron, Adam, Dell, and Kain are Project leads.
