### ISSUE TITLE
Content Leads Kickoff Meeting

### ISSUE THREAD

**Issue by ktabarez** [missionfed/training#4]
##### Meeting Lead
- Kain
##### Presenters
- Kain
##### Meeting Minutes Recorder
- Kain
##### Obstacles
- N/A
##### Current Work Items
- Create GitHub accounts
##### Outline
- Meet with GitHub leads to go over their role:
  - Manage Wiki
  - Organize files
  - Convert meeting minutes to markup
  - Create issues and perform assignments
  - Organize issues into milestones, and make sure milestones have due dates
  - Other...
- Create GitHub accounts
##### Decisions Made
- N/A
##### Follow-up Action Items
- Due Dates
  - N/A

**Comment by delljordan** [comment]
DONE!

**Comment by martinezrey** [comment]
### We had our Content Leads kickoff meeting this morning. Here are the meeting minutes:

#### Meeting Objective
- Further define Content Lead role, duties, and responsibilities
- Get them caught up with how to use GitHub

#### Attendees:
- John @johnrward 
- Dell @delljordan 
- Rey @martinezrey
- Kain @ktabarez 

#### Summary
- Walked through how to manage issues, milestones, and labeling.

![screenshot_labels](https://raw.githubusercontent.com/missionfed/training/master/images/06142016.png)
- Explained what milestones are, how to create them and link issues to them.

#### Decisions Made
- None

#### Follow-up Action Items
- Organize content by type of training
- Organize issues, labels, and make sure every issue is assigned to someone
- Decide if we should  use the wiki or the project landing page to keep track of links and the direction we are heading
- Setup GitHub Accounts for all team members
- Remove completed issues
- Get familiar with GitHub

#### Completed Work Items
-  @delljordan  and @johnrward signed up for GitHub

**Comment by ktabarez** [comment]
Closing. Follow-up action items have been converted to todo's
